<a href="https://colab.research.google.com/github/lizezhonglaile/colabTest/blob/main/hmm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install hmmlearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [13]:

import numpy as np
from hmmlearn import hmm
 
states = ['晴', '阴','雨']
n_states = len(states)
 
observations = ['读书', '打球','访友','读书']
n_observations = len(observations)
 
start_probability = np.array([0.5, 0.3, 0.2])
 
transition_probability = np.array([
  [0.7, 0.2, 0.1],
  [0.3, 0.5, 0.2],
  [0.3, 0.4, 0.3]
])
 
emission_probability = np.array([
  [0.3, 0.4, 0.3],
  [0.3, 0.2, 0.5],
  [0.8, 0.1, 0.1]
])
 
model = hmm.MultinomialHMM(n_components=n_states)
model.startprob_=start_probability
model.transmat_=transition_probability
model.emissionprob_=emission_probability
print(model.startprob_)
print(model.transmat_)
print(model.emissionprob_)
observe_chain=np.array([0,1,2,0]).reshape(-1,1)
print(model.score(observe_chain))
print(model.predict(observe_chain))

[0.5 0.3 0.2]
[[0.7 0.2 0.1]
 [0.3 0.5 0.2]
 [0.3 0.4 0.3]]
[[0.3 0.4 0.3]
 [0.3 0.2 0.5]
 [0.8 0.1 0.1]]
-4.311426522157715
[0 0 0 0]


In [ ]:
print("test")

test


# 新段落

In [9]:
# f = open("out.txt", "w")
# f.write("asdfasdf")
# f.close()
# !pwd

from google.colab import drive
drive.mount('/content/drive')
!pwd
!cp /content/out.txt ./drive/MyDrive/

Mounted at /content/drive
/content


In [12]:
!cp /content/out.txt ./drive/MyDrive/
!ls -l ./drive/MyDrive/*

-rw------- 1 root root    8 Jun  7 08:51 ./drive/MyDrive/out.txt

./drive/MyDrive/colab:
total 4
drwx------ 2 root root 4096 Jun  7 07:23 awesome_chinese
